- hosts: all
  gather_facts: false

  tasks:
    - name: debug 1
      debug:
        msg: hello 1-2
      tags:
        - d1

    - name: debug 2
      debug:
        msg: hello 2
      tags:
        - d2
