- hosts: all
  gather_facts: false

  tasks:
    - name: fail
      fail:
        msg: "This is a failure message for debug 1"
      when:
        - inventory_hostname == "host02"
    - name: debug 2
      debug:
        msg: "hello"
