---
- hosts: ios
  gather_facts: false
    
  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - name: show ip route cisco.ios.ios_command
      ios_command: 
        commands:
          - show ip route
      register: result_ip_route

    - name: show ip route
      debug:
        msg: "{{ result_ip_route }}"

- hosts: servers
  gather_facts: false
    
  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - name: command
      command: 
        cmd: id
