- hosts: ios
  gather_facts: false
    
  tasks:
#     - name: pause
#       pause:
#         seconds: 60
        
    - name: show ip route cisco.ios.ios_command
      ios_command: 
        commands:
          - show ip route
      register: result_ip_route

    - name: show ip route
      debug:
        msg: "{{ result_ip_route }}"

#     - name: gather ios_facts
#       ios_facts:
#         gather_subset: 
#           - "hardware"
    
#     - name: debug ios_facts
#       debug:
#         var: ansible_facts.net_version
